/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.TravelAgency.AirlineDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Prabhu Surbamanian
 */
public class MainTravelAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form leftControlPanel
     */
    private AirlineDirectory airlineDirectory;
    private JPanel rightJPanel;
    
    public MainTravelAgencyJPanel(JPanel rightJPanel, AirlineDirectory airlineDirectory) {
        initComponents();
        this.airlineDirectory = airlineDirectory;
        this.rightJPanel = rightJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightManagerBtn = new javax.swing.JButton();
        masterScheduleBtn = new javax.swing.JButton();
        airlineAdderBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        flightManagerBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        flightManagerBtn.setText("Flight Manager");
        flightManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightManagerBtnActionPerformed(evt);
            }
        });

        masterScheduleBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        masterScheduleBtn.setText("Master Schedule");
        masterScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterScheduleBtnActionPerformed(evt);
            }
        });

        airlineAdderBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        airlineAdderBtn.setText("Add Airline");
        airlineAdderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineAdderBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(masterScheduleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(flightManagerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(airlineAdderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(airlineAdderBtn)
                .addGap(34, 34, 34)
                .addComponent(flightManagerBtn)
                .addGap(18, 18, 18)
                .addComponent(masterScheduleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flightManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightManagerBtnActionPerformed
        // TODO add your handling code here:
        AirlinesManageJPanel airlinePanel = new AirlinesManageJPanel(rightJPanel, airlineDirectory);
        rightJPanel.add("AirlinesManageJPanel", airlinePanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
        /*
        AirlinesManageJPanel airlinePanel = new AirlinesManageJPanel(rightJPanel, airlineList);
        rightJPanel.add("AirlinesManageJPanel", airlinePanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);*/
    }//GEN-LAST:event_flightManagerBtnActionPerformed

    private void masterScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterScheduleBtnActionPerformed
        // TODO add your handling code here:
        ScheduleManageJPanel scheduleManager  = new ScheduleManageJPanel(rightJPanel, airlineDirectory);
        rightJPanel.add("ScheduleManageJPanel", scheduleManager);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_masterScheduleBtnActionPerformed

    private void airlineAdderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineAdderBtnActionPerformed
        // TODO add your handling code here:
        CreateAirlineJPanel createAirline = new CreateAirlineJPanel(rightJPanel, airlineDirectory);
        rightJPanel.add("CreateAirlineJPanel", createAirline);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_airlineAdderBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlineAdderBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton flightManagerBtn;
    private javax.swing.JButton masterScheduleBtn;
    // End of variables declaration//GEN-END:variables
}
