/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.TravelAgency.Airline;
import Business.TravelAgency.AirlineDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Prabhu Surbamanian
 */
public class MainTravelAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form leftControlPanel
     */
    private AirlineDirectory airlineDirectory;
    private Airline airline;
    private JPanel rightJPanel;
    
    public MainTravelAgencyJPanel(JPanel rightJPanel, AirlineDirectory airlineDirectory) {
        initComponents();
        this.airlineDirectory = airlineDirectory;
        this.rightJPanel = rightJPanel;
        this.airline = airline;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightManagerBtn = new javax.swing.JButton();
        masterScheduleBtn = new javax.swing.JButton();
        airlineAdderBtn = new javax.swing.JButton();
        userBookedBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        flightManagerBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flightManagerBtn.setText("Airlines/Flight Manager>>");
        flightManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightManagerBtnActionPerformed(evt);
            }
        });

        masterScheduleBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        masterScheduleBtn.setText("Master Schedule>>");
        masterScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterScheduleBtnActionPerformed(evt);
            }
        });

        airlineAdderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        airlineAdderBtn.setText("Add Airline>>");
        airlineAdderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineAdderBtnActionPerformed(evt);
            }
        });

        userBookedBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userBookedBtn.setText("Users Booked>>");
        userBookedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBookedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userBookedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(airlineAdderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(masterScheduleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(flightManagerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(airlineAdderBtn)
                .addGap(21, 21, 21)
                .addComponent(flightManagerBtn)
                .addGap(93, 93, 93)
                .addComponent(masterScheduleBtn)
                .addGap(18, 18, 18)
                .addComponent(userBookedBtn)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flightManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightManagerBtnActionPerformed
        // TODO add your handling code here:
        AirlinesManageJPanel airlinePanel = new AirlinesManageJPanel(rightJPanel, airlineDirectory);
        rightJPanel.add("AirlinesManageJPanel", airlinePanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
        /*
        AirlinesManageJPanel airlinePanel = new AirlinesManageJPanel(rightJPanel, airlineList);
        rightJPanel.add("AirlinesManageJPanel", airlinePanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);*/
    }//GEN-LAST:event_flightManagerBtnActionPerformed

    private void masterScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterScheduleBtnActionPerformed
        // TODO add your handling code here:
        
        ScheduleManageJPanel scheduleManager  = new ScheduleManageJPanel(rightJPanel, airline, airlineDirectory);
        rightJPanel.add("ScheduleManageJPanel", scheduleManager);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_masterScheduleBtnActionPerformed

    private void airlineAdderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineAdderBtnActionPerformed
        // TODO add your handling code here:
        CreateAirlineJPanel createAirline = new CreateAirlineJPanel(rightJPanel, airlineDirectory);
        rightJPanel.add("CreateAirlineJPanel", createAirline);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_airlineAdderBtnActionPerformed

    private void userBookedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBookedBtnActionPerformed
        // TODO add your handling code here:
        UserDirectoryJPanel userDirectory = new UserDirectoryJPanel(rightJPanel, airlineDirectory);
        rightJPanel.add("CreateAirlineJPanel", userDirectory);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_userBookedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlineAdderBtn;
    private javax.swing.JButton flightManagerBtn;
    private javax.swing.JButton masterScheduleBtn;
    private javax.swing.JButton userBookedBtn;
    // End of variables declaration//GEN-END:variables
}
