/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.AirlinerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Prabhu Surbamanian
 */
public class TravelAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form leftControlPanel
     */
    private AirlinerDirectory airlineList;
    private JPanel rightJPanel;
    
    public TravelAgencyJPanel(JPanel rightJPanel, AirlinerDirectory airlineList) {
        initComponents();
        this.airlineList = airlineList;
        this.rightJPanel = rightJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlineManagerBtn = new javax.swing.JButton();
        masterScheduleBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        airlineManagerBtn.setText("Airline Manager");
        airlineManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineManagerBtnActionPerformed(evt);
            }
        });

        masterScheduleBtn.setText("Master Schedule");
        masterScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterScheduleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(airlineManagerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(masterScheduleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(airlineManagerBtn)
                .addGap(43, 43, 43)
                .addComponent(masterScheduleBtn)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void airlineManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineManagerBtnActionPerformed
        // TODO add your handling code here:
        CreateAirlineJPanel createAirline = new CreateAirlineJPanel(rightJPanel, airlineList);
        rightJPanel.add("CreateAirlineJPanel", createAirline);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
        
        /*AirlinesManageJPanel airlinePanel = new AirlinesManageJPanel(rightJPanel, airlineList);
        rightJPanel.add("AirlinesManageJPanel", airlinePanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);*/
        
    }//GEN-LAST:event_airlineManagerBtnActionPerformed

    private void masterScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterScheduleBtnActionPerformed
        // TODO add your handling code here:
        AirlinesManageJPanel airlinePanel = new AirlinesManageJPanel(rightJPanel, airlineList);
        rightJPanel.add("AirlinesManageJPanel", airlinePanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_masterScheduleBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlineManagerBtn;
    private javax.swing.JButton masterScheduleBtn;
    // End of variables declaration//GEN-END:variables
}
