/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Report.Person;
import Report.Demographic;
import Report.Address;
import Report.Bank;
import Report.DriverLicense;
import Report.MedicalRecord;

/**
 *
 * @author Prabhu Surbamanian
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    private Demographic demographic;
    private Address address;
    private Bank savingBank;
    private Bank checkingBank;
    private DriverLicense driverLicense;
    private MedicalRecord medicalRecord;
       
    public MainJFrame() {
        initComponents();
        person = new Person();
        /*
        demographic = new Demographic();
        address = new Address();
        savingBank = new Bank();
        checkingBank = new Bank();
        driverLicense = new DriverLicense();
        medicalRecord = new MedicalRecord();
        */
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        CreateDemographicInfoBtn = new javax.swing.JButton();
        CreateAddressBtn = new javax.swing.JButton();
        CreateSavingAccountBtn = new javax.swing.JButton();
        CreateCheckingAccountBtn = new javax.swing.JButton();
        CreateDriversLicenceBtn = new javax.swing.JButton();
        CreateMedicalDetailsBtn = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        displayJPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        splitPane.setPreferredSize(new java.awt.Dimension(1280, 720));

        controlJPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        controlJPanel.setAutoscrolls(true);
        controlJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CreateDemographicInfoBtn.setText("Demographic");
        CreateDemographicInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDemographicInfoBtnActionPerformed(evt);
            }
        });

        CreateAddressBtn.setText("Address");
        CreateAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAddressBtnActionPerformed(evt);
            }
        });

        CreateSavingAccountBtn.setText("Saving Account");
        CreateSavingAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateSavingAccountBtnActionPerformed(evt);
            }
        });

        CreateCheckingAccountBtn.setText("Checking Account");
        CreateCheckingAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCheckingAccountBtnActionPerformed(evt);
            }
        });

        CreateDriversLicenceBtn.setText("Driver's Licence");
        CreateDriversLicenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDriversLicenceBtnActionPerformed(evt);
            }
        });

        CreateMedicalDetailsBtn.setText("Medical Detials");
        CreateMedicalDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMedicalDetailsBtnActionPerformed(evt);
            }
        });

        Report.setText("Report");
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CreateDemographicInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateAddressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateSavingAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateCheckingAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateDriversLicenceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateMedicalDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlJPanelLayout.createSequentialGroup()
                        .addComponent(Report)
                        .addGap(43, 43, 43)))
                .addGap(19, 19, 19))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(CreateDemographicInfoBtn)
                .addGap(21, 21, 21)
                .addComponent(CreateAddressBtn)
                .addGap(21, 21, 21)
                .addComponent(CreateSavingAccountBtn)
                .addGap(21, 21, 21)
                .addComponent(CreateCheckingAccountBtn)
                .addGap(21, 21, 21)
                .addComponent(CreateDriversLicenceBtn)
                .addGap(21, 21, 21)
                .addComponent(CreateMedicalDetailsBtn)
                .addGap(102, 102, 102)
                .addComponent(Report)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlJPanel);

        displayJPane.setAutoscrolls(true);
        displayJPane.setPreferredSize(new java.awt.Dimension(900, 720));
        splitPane.setRightComponent(displayJPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateSavingAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateSavingAccountBtnActionPerformed
        // TODO add your handling code here:
        CreateSavingJPanel savingPanel = new CreateSavingJPanel(person);
        splitPane.setRightComponent(savingPanel);
    }//GEN-LAST:event_CreateSavingAccountBtnActionPerformed

    private void CreateDemographicInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDemographicInfoBtnActionPerformed
        // TODO add your handling code here:
        CreateDemographicJPanel demographicPanel = new CreateDemographicJPanel(person);
        splitPane.setRightComponent(demographicPanel);
    }//GEN-LAST:event_CreateDemographicInfoBtnActionPerformed

    private void CreateAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAddressBtnActionPerformed
        // TODO add your handling code here:
        CreateAddressJPanel addressPanel = new CreateAddressJPanel(person);
        splitPane.setRightComponent(addressPanel);
    }//GEN-LAST:event_CreateAddressBtnActionPerformed

    private void CreateCheckingAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCheckingAccountBtnActionPerformed
        // TODO add your handling code here:
        CreateCheckingJPanel checkingPanel = new CreateCheckingJPanel(person);
        splitPane.setRightComponent(checkingPanel);
    }//GEN-LAST:event_CreateCheckingAccountBtnActionPerformed

    private void CreateDriversLicenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDriversLicenceBtnActionPerformed
        // TODO add your handling code here:
        CreateDriverLicenseJPanel driverPanel = new CreateDriverLicenseJPanel(person);
        splitPane.setRightComponent(driverPanel);
    }//GEN-LAST:event_CreateDriversLicenceBtnActionPerformed

    private void CreateMedicalDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMedicalDetailsBtnActionPerformed
        // TODO add your handling code here:
        CreateMedicalRecordJPanel medicalPanel = new CreateMedicalRecordJPanel(person);
        splitPane.setRightComponent(medicalPanel);
    }//GEN-LAST:event_CreateMedicalDetailsBtnActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
        ReportJPanel reportPanel = new ReportJPanel(person);
        /*
        ReportJPanel reportPanel = new ReportJPanel(demographic,address,savingBank,
                                                    checkingBank,driverLicense,medicalRecord);
        */
        splitPane.setRightComponent(reportPanel);
        
    }//GEN-LAST:event_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAddressBtn;
    private javax.swing.JButton CreateCheckingAccountBtn;
    private javax.swing.JButton CreateDemographicInfoBtn;
    private javax.swing.JButton CreateDriversLicenceBtn;
    private javax.swing.JButton CreateMedicalDetailsBtn;
    private javax.swing.JButton CreateSavingAccountBtn;
    private javax.swing.JButton Report;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JScrollPane displayJPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
